---

- name: Ensure required packages are installed
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{varnish_required_packages}}"


- name: Add Varnish apt key.
  apt_key: url="{{varnish_gpg_key}}" state=present

- name: Add Varnish apt repository.
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: "{{ varnish_repos }}"


- name: Install Varnish.
  apt: name=varnish state=installed

- name: Copy Varnish configuration.
  template:
    src: varnish.j2
    dest: "{{ varnish_sysvinit_config_path }}/varnish"
    owner: root
    group: root
    mode: 0644

- name: Update systemd configuration
  template:
    src: varnish.service.j2
    dest: "{{varnish_systemd_config_path}}/varnish.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart varnish

# by default the varnishlog services are not running
# so we don't want to rotate the logs if they are empty
- name: Create logrotate entry for varnish.log
  template:
    src: logrotate_varnish.j2
    dest: "/etc/logrotate.d/varnish"
    owner: root
    group: root
    mode: 0644
  become: true
