---
- name: Add Varnish apt key.
  apt_key: url=http://repo.varnish-cache.org/debian/GPG-key.txt state=present

- name: Add Varnish apt repository.
  apt_repository:
    repo: "deb http://repo.varnish-cache.org/ubuntu {{ ansible_distribution_release }} varnish-4.0"
    state: present

- name: Install Varnish.
  apt: name=varnish state=installed

- name: Copy Varnish configuration.
  template:
    src: varnish.j2
    dest: /etc/default/varnish
    owner: root
    group: root
    mode: 0755

- name: Update systemd configuration
  template:
    src: varnish.service.j2
    dest: /lib/systemd/system/varnish.service
    owner: root
    group: root
    mode: 0755
  notify:
    - reload systemd
    - restart varnish

# by default the varnishlog services are not running
# so we don't want to rotate the logs if they are empty
- name: Create logrotate entry for varnish.log
  template:
    src: logrotate_varnish.j2
    dest: "/etc/logrotate.d/varnish"
    owner: root
    group: root
    mode: 0644
  sudo: true