---
- name: Add Varnish apt key.
  apt_key: url=http://repo.varnish-cache.org/debian/GPG-key.txt state=present

- name: Add Varnish apt repository.
  apt_repository:
    repo: "deb http://repo.varnish-cache.org/ubuntu {{ ansible_distribution_release }} varnish-4.0"
    state: present

- name: Install Varnish.
  apt: name=varnish state=installed

- name: Copy Varnish configuration.
  template:
    src: varnish.j2
    dest: /etc/default/varnish
    owner: root
    group: root
    mode: 0755

- name: Update systemd configuration
  lineinfile:
     dest: /lib/systemd/system/varnish.service
     line: 'ExecStart=/usr/sbin/varnishd -a :{{varnish_listen_port}} -T localhost:{{varnish_admin_listen_port}} -f {{ varnish_config_path }}/{{ varnish_default_vcl }} -S /etc/varnish/secret -s malloc,256m'
              state=present
              backup=yes"
  sudo: true
  tags:
    - configuration
    - rootmail
  notify:
    - restart exim4
