---

- block:
    - name: Ensure required packages are installed
      package:
        name: "{{ item }}"
        state: present
      with_items: "{{varnish_required_packages}}"


    - name: Install repository management dependencies
      ansible.builtin.apt:
        name: python3-debian
        state: present

    - name: Add Varnish apt key.
      ansible.builtin.get_url:
        url: "{{ varnish_gpg_key }}"
        dest: /etc/apt/trusted.gpg.d/varnish.asc
        mode: "0644"

    - name: Remove legacy Varnish apt repository list file.
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/varnish.list
        state: absent

    - name: Add Varnish apt repository.
      ansible.builtin.deb822_repository:
        name: varnish
        types: "{{ varnish_repo_types }}"
        uris: "{{ varnish_repo_uri }}"
        suites: "{{ ansible_distribution_release }}"
        components: main
        signed_by: /etc/apt/trusted.gpg.d/varnish.asc
        state: present

  when: ansible_distribution == 'Debian' and ansible_lsb.major_release|int < 11

- name: Install Varnish.
  apt: name=varnish state=present

- name: Copy Varnish configuration.
  template:
    src: varnish.j2
    dest: "{{ varnish_sysvinit_config_path }}/varnish"
    owner: root
    group: root
    mode: 0644

- name: Update systemd configuration
  template:
    src: varnish.service.j2
    dest: "{{varnish_systemd_config_path}}/varnish.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart varnish

# by default the varnishlog services are not running
# so we don't want to rotate the logs if they are empty
- name: Create logrotate entry for varnish.log
  template:
    src: logrotate_varnish.j2
    dest: "/etc/logrotate.d/varnish"
    owner: root
    group: root
    mode: 0644
  become: true
